# These parameters are tuned for xx1

/**:
  ros__parameters:
    transition_timeout: 6.0
    frequency_hz: 10.0
    check_engage_condition: true # set false if you do not want to care about the engage condition.
    nearest_dist_deviation_threshold: 3.0 # [m] for finding nearest index
    nearest_yaw_deviation_threshold: 1.57 # [rad] for finding nearest index
    engage_acceptable_limits:
      allow_autonomous_in_stopped: true  # no check if the velocity is zero, always allowed.
      dist_threshold: 0.5
      yaw_threshold: 0.524
      speed_upper_threshold: 10.0
      speed_lower_threshold: -10.0
      acc_threshold: 1.5
      lateral_acc_threshold: 1.0
      lateral_acc_diff_threshold: 0.5
    stable_check:
      duration: 3.0
      dist_threshold: 0.5
      speed_upper_threshold: 2.0
      speed_lower_threshold: -2.0
      yaw_threshold: 0.262
