/**:
  ros__parameters:
    event_diag_list:
      # Hardware
      # CPU
      CPU-001: "cpu_monitor: CPU Temperature"
      CPU-002: "cpu_monitor: CPU Usage"
      CPU-003: "cpu_monitor: CPU Load Average"
      CPU-004: "cpu_monitor: CPU Thermal Throttling"
      CPU-005: "cpu_monitor: CPU Frequency"

      # HDD
      HDD-001: "hdd_monitor: HDD Temperature"
      HDD-002: "hdd_monitor: HDD Usage"
      HDD-003: "hdd_monitor: HDD Connection"
      HDD-004: "hdd_monitor: HDD TotalDataWritten"
      HDD-005: "hdd_monitor: HDD PowerOnHours"
      HDD-006: "hdd_monitor: HDD RecoveredError"
      HDD-007-1: "hdd_monitor: HDD ReadDataRate"
      HDD-007-2: "hdd_monitor: HDD WriteDataRate"
      HDD-007-3: "hdd_monitor: HDD ReadIOPS"
      HDD-007-4: "hdd_monitor: HDD WriteIOPS"

      # Memory
      MEM-001: "mem_monitor: Memory Usage"
      MEM-002: "mem_monitor: Memory ECC"

      # Network
      NET-001: "net_monitor: Network Usage"
      NET-002: "net_monitor: Network Traffic"
      NET-003: "net_monitor: Network CRC Error"
      NET-004: "net_monitor: IP Packet Reassembles Failed"

      # NTP
      NTP-001: "ntp_monitor: NTP Offset"

      # Process
      PRO-001: "process_monitor: Tasks Summary"
      PRO-002-0: "process_monitor: High-load Proc[0]"
      PRO-002-1: "process_monitor: High-load Proc[1]"
      PRO-002-2: "process_monitor: High-load Proc[2]"
      PRO-002-3: "process_monitor: High-load Proc[3]"
      PRO-002-4: "process_monitor: High-load Proc[4]"
      PRO-003-0: "process_monitor: High-mem Proc[0]"
      PRO-003-1: "process_monitor: High-mem Proc[1]"
      PRO-003-2: "process_monitor: High-mem Proc[2]"
      PRO-003-3: "process_monitor: High-mem Proc[3]"
      PRO-003-4: "process_monitor: High-mem Proc[4]"

      # GPU
      GPU-001: "gpu_monitor: GPU Temperature"
      GPU-002: "gpu_monitor: GPU Usage"
      GPU-003: "gpu_monitor: GPU Memory Usage"
      GPU-004: "gpu_monitor: GPU Thermal Throttling"
      GPU-005: "gpu_monitor: GPU Frequency"

      # BIOS
      BIOS-001: "voltage_monitor: CMOS Battery Status"

      # IMU
      IMU-001: "imu_monitor: yaw_rate_status"
      IMU-003: "gyro_bias_estimator: gyro_bias_validator"

      # LiDAR
      PNDR-001/front_lower: "pandar_monitor: /sensing/lidar/front_lower: pandar_connection"
      PNDR-001/front_upper: "pandar_monitor: /sensing/lidar/front_upper: pandar_connection"
      PNDR-001/left_lower: "pandar_monitor: /sensing/lidar/left_lower: pandar_connection"
      PNDR-001/left_upper: "pandar_monitor: /sensing/lidar/left_upper: pandar_connection"
      PNDR-001/right_lower: "pandar_monitor: /sensing/lidar/right_lower: pandar_connection"
      PNDR-001/right_upper: "pandar_monitor: /sensing/lidar/right_upper: pandar_connection"
      PNDR-001/rear_lower: "pandar_monitor: /sensing/lidar/rear_lower: pandar_connection"
      PNDR-001/rear_upper: "pandar_monitor: /sensing/lidar/rear_upper: pandar_connection"
      PNDR-002/front_lower: "pandar_monitor: /sensing/lidar/front_lower: pandar_temperature"
      PNDR-002/front_upper: "pandar_monitor: /sensing/lidar/front_upper: pandar_temperature"
      PNDR-002/left_lower: "pandar_monitor: /sensing/lidar/left_lower: pandar_temperature"
      PNDR-002/left_upper: "pandar_monitor: /sensing/lidar/left_upper: pandar_temperature"
      PNDR-002/right_lower: "pandar_monitor: /sensing/lidar/right_lower: pandar_temperature"
      PNDR-002/right_upper: "pandar_monitor: /sensing/lidar/right_upper: pandar_temperature"
      PNDR-002/rear_lower: "pandar_monitor: /sensing/lidar/rear_lower: pandar_temperature"
      PNDR-002/rear_upper: "pandar_monitor: /sensing/lidar/rear_upper: pandar_temperature"
      PNDR-003/front_lower: "pandar_monitor: /sensing/lidar/front_lower: pandar_ptp"
      PNDR-003/front_upper: "pandar_monitor: /sensing/lidar/front_upper: pandar_ptp"
      PNDR-003/left_lower: "pandar_monitor: /sensing/lidar/left_lower: pandar_ptp"
      PNDR-003/left_upper: "pandar_monitor: /sensing/lidar/left_upper: pandar_ptp"
      PNDR-003/right_lower: "pandar_monitor: /sensing/lidar/right_lower: pandar_ptp"
      PNDR-003/right_upper: "pandar_monitor: /sensing/lidar/right_upper: pandar_ptp"
      PNDR-003/rear_lower: "pandar_monitor: /sensing/lidar/rear_lower: pandar_ptp"
      PNDR-003/rear_upper: "pandar_monitor: /sensing/lidar/rear_upper: pandar_ptp"

      # Software
      # Map
      MAP-001-1: "topic_state_monitor_vector_map: map_topic_status"
      MAP-001-2: "topic_state_monitor_pointcloud_map: map_topic_status"

      # Localization
      LOCALIZATION-001-1: "topic_state_monitor_initialpose3d: localization_topic_status"
      LOCALIZATION-001-2: "topic_state_monitor_pose_twist_fusion_filter_pose: localization_topic_status"
      LOCALIZATION-001-3: "topic_state_monitor_transform_map_to_base_link: localization_topic_status"
      LOCALIZATION-004: "localization_error_monitor: localization_accuracy"
      LOCALIZATION-005: "localization_error_monitor: localization_accuracy_lateral_direction"

      # Perception
      PERCEPTION-001-1: "topic_state_monitor_traffic_light_recognition_traffic_signals: perception_topic_status"
      PERCEPTION-001-2: "topic_state_monitor_object_recognition_objects: perception_topic_status"
      PERCEPTION-001-3: "topic_state_monitor_obstacle_segmentation_pointcloud: perception_topic_status"

      # Planning
      PLANNING-001-1: "topic_state_monitor_mission_planning_route: planning_topic_status"
      PLANNING-001-2: "topic_state_monitor_scenario_planning_trajectory: planning_topic_status"
      PLANNING-003: "planning_validator: trajectory_validation_finite"
      PLANNING-004: "planning_validator: trajectory_validation_interval"
      PLANNING-005: "planning_validator: trajectory_validation_curvature"
      PLANNING-006: "planning_validator: trajectory_validation_relative_angle"
      PLANNING-007: "planning_validator: trajectory_validation_lateral_acceleration"
      PLANNING-008: "planning_validator: trajectory_validation_acceleration"
      PLANNING-009: "planning_validator: trajectory_validation_deceleration"
      PLANNING-010: "planning_validator: trajectory_validation_steering"
      PLANNING-011: "planning_validator: trajectory_validation_steering_rate"
      PLANNING-012: "planning_validator: trajectory_validation_velocity_deviation"
      PLANNING-013: "collision_checker: collision_check"

      # Control
      CONTROL-001: "topic_state_monitor_control_command_control_cmd: control_topic_status"
      CONTROL-002: "external_cmd_converter: remote_control_topic_status"
      CONTROL-003: "vehicle_cmd_gate: heartbeat"
      CONTROL-004: "lane_departure_checker_node: lane_departure"
      CONTROL-005: "lane_departure_checker_node: trajectory_deviation"
      CONTROL-008: "external_cmd_selector: heartbeat"
      CONTROL-009: "autonomous_emergency_braking: aeb_emergency_stop"
      CONTROL-010: "control_validator: control_validation_max_distance_deviation"

      # Vehicle
      VEHICLE-001-1: "topic_state_monitor_vehicle_status_velocity_status: vehicle_topic_status"
      VEHICLE-001-2: "topic_state_monitor_vehicle_status_steering_status: vehicle_topic_status"
      VEHICLE-005: "j6_interface: vehicle_heartbeat_errors"
      VEHICLE-006: "j6_interface: vehicle_errors"

      # System
      SYSTEM-001: "topic_state_monitor_system_emergency_control_cmd: system_topic_status"
      SYSTEM-002: "vehicle_cmd_gate: emergency_stop_operation"
      SYSTEM-003: "bagpacker_state"
      SYSTEM-005: "edge_core_internet_connection"

      # Others
      OTHERS-002/front_lower: "blockage_return_diag: /sensing/lidar/front_lower: blockage_validation"
      OTHERS-002/front_upper: "blockage_return_diag: /sensing/lidar/front_upper: blockage_validation"
      OTHERS-002/left_lower: "blockage_return_diag: /sensing/lidar/left_lower: blockage_validation"
      OTHERS-002/left_upper: "blockage_return_diag: /sensing/lidar/left_upper: blockage_validation"
      OTHERS-002/right_lower: "blockage_return_diag: /sensing/lidar/right_lower: blockage_validation"
      OTHERS-002/right_upper: "blockage_return_diag: /sensing/lidar/right_upper: blockage_validation"
      OTHERS-002/rear_lower: "blockage_return_diag: /sensing/lidar/rear_lower: blockage_validation"
      OTHERS-002/rear_upper: "blockage_return_diag: /sensing/lidar/rear_upper: blockage_validation"
      OTHERS-004: "concatenate_data: concat_status"
      OTHERS-005/left_upper: "dual_return_filter: /sensing/lidar/left_upper: visibility_validation"
      OTHERS-005/right_upper: "dual_return_filter: /sensing/lidar/right_upper: visibility_validation"
      OTHERS-010: "emergency_vehicle_detector: emergency_vehicle"

      # Not in System_Hazard_and_Fail_Safe
      debug_data_logger_disk_usage_error: "bagpacker_state/disk_usage"
      slip_status: "slip_detector: slip_status"
      daytime_status: "daytime_monitor: daytime_status"
      perception_delay_check: "multi_object_tracker: Perception delay check from original header stamp"
      imu_topic_status: "topic_state_monitor_imu_data: imu_topic_status"
      gnss_topic_status: "topic_state_monitor_gnss_pose: gnss_topic_status"
      septentrio_status: "septentrio_driver: Quality indicators"
      /sensing/camera/0/connection: "topic_state_monitor_camera0: camera0_topic_status"
      /sensing/camera/1/connection: "topic_state_monitor_camera0: camera1_topic_status"
      /sensing/camera/2/connection: "topic_state_monitor_camera0: camera2_topic_status"
      /sensing/camera/3/connection: "topic_state_monitor_camera0: camera3_topic_status"
      /sensing/camera/4/connection: "topic_state_monitor_camera0: camera4_topic_status"
      /sensing/camera/5/connection: "topic_state_monitor_camera0: camera5_topic_status"
      /sensing/camera/6/connection: "topic_state_monitor_camera0: camera6_topic_status"
      /sensing/camera/7/connection: "topic_state_monitor_camera0: camera7_topic_status"
      /sensing/radar/front_center/connection: "topic_state_monitor_radar_front_center: radar_front_center_topic_status"
      /sensing/radar/front_left/connection: "topic_state_monitor_radar_front_left: radar_front_left_topic_status"
      /sensing/radar/front_right/connection: "topic_state_monitor_radar_front_right: radar_front_right_topic_status"
      /sensing/radar/rear_center/connection: "topic_state_monitor_radar_rear_center: radar_rear_center_topic_status"
      /sensing/radar/rear_left/connection: "topic_state_monitor_radar_rear_left: radar_rear_left_topic_status"
      /sensing/radar/rear_right/connection: "topic_state_monitor_radar_rear_right: radar_rear_right_topic_status"
